version: "3.9"

services:
  telegram_media_downloader:
    image: tangyoha/telegram_media_downloader:latest
    build: .
    ports:
      # Here is what you need to edit
      - "5000:5000"
    volumes:
      # Here is what you need to edit
      # - "/root/downloads/:/app/downloads/"
      # The following is what you don't need to edit
      # enable config
      # - "./config.yaml:/app/config.yaml"
      # enable data
      # - "./data.yaml:/app/data.yaml"
      #  enable log
      "./log/:/app/log/"
      - "sessions:/app/sessions"
      - "temp:/app/temp"

volumes:
  sessions:
  temp:
